import type { Metadata } from "next";
import { DemoCandidateReportView } from "./demo-candidate-report-view";

/**
 * Public example of the hiring-manager candidate report.
 *
 * `/demo` is outside middleware's protected prefixes, so this renders with no
 * session — the point is a link that can be sent to someone outside the
 * organisation. It contains no real candidate data: every score comes from a
 * frozen fixture generated by the backend's own scorers.
 */
export const metadata: Metadata = {
  title: "Example candidate report",
  // A public page showing the internal report layout should not be indexed.
  robots: { index: false, follow: false },
};

export default function DemoCandidateReportPage() {
  return <DemoCandidateReportView />;
}
