import {
  mapFirebaseReportToHmResult,
  type FirebaseAssignmentAssessmentReport,
} from "@/lib/hm-assessment-progress";
import { validateCandidateReport } from "@/lib/hiring-manager/validate-report";
import type { HiringManagerCandidateReport } from "@/types/hiring-manager.types";
import fixture from "./demo-candidate-report.json";

/**
 * Frozen demo reports for /demo/candidate-report.
 *
 * The scores, competencies, flags and insight copy in the JSON are generated by
 * the backend's own scorers and report projection — see
 * `Platform/firebase-backend/scripts/generate-demo-report.ts`. Nothing here
 * invents a number, so the demo cannot show behaviour the product does not have.
 *
 * The rows are deliberately put through `mapFirebaseReportToHmResult` and
 * `validateCandidateReport`, the same two steps the authenticated report takes,
 * rather than being shaped for the view directly. If a fixture ever drifts from
 * the report contract, `parseReportMetrics` strips its metrics and the
 * breakdown disappears — which is a visible failure during development rather
 * than a quietly degraded report in front of a client.
 */

export type DemoProfile = "strong" | "borderline";

type DemoRow = FirebaseAssignmentAssessmentReport & {
  title: string;
  weight: number;
};

type DemoCandidate = {
  profile: DemoProfile;
  sessionId: string;
  candidate: { documentId: string; name: string; email: string };
  campaign: {
    documentId: string;
    name: string;
    role: string;
    assessmentStack: string[];
  };
  assessmentSession: { documentId: string; name: string; startsAt: string };
  compositeScore: number;
  hmDecision: "pending";
  clientReviewStatus: "pending_review";
  results: DemoRow[];
};

function buildReport(entry: DemoCandidate): HiringManagerCandidateReport {
  return validateCandidateReport({
    sessionId: entry.sessionId,
    candidate: entry.candidate,
    campaign: {
      ...entry.campaign,
      resolvedStackSummary: null,
    },
    assessmentSession: entry.assessmentSession,
    compositeScore: entry.compositeScore,
    hmDecision: entry.hmDecision,
    clientReviewStatus: entry.clientReviewStatus,
    // Title and campaign weight come from the campaign row in production, so
    // they are reapplied after the shared mapping rather than being invented
    // inside it.
    results: entry.results.map((row) => ({
      ...mapFirebaseReportToHmResult(row),
      title: row.title,
      weight: row.weight,
    })),
  });
}

const candidates = (fixture as { candidates: DemoCandidate[] }).candidates;

export const DEMO_REPORTS: ReadonlyArray<{
  profile: DemoProfile;
  label: string;
  summary: string;
  report: HiringManagerCandidateReport;
}> = candidates.map((entry) => ({
  profile: entry.profile,
  label: entry.candidate.name,
  summary:
    entry.profile === "strong"
      ? "Meets every assessment standard"
      : "Below standard on four of five",
  report: buildReport(entry),
}));
